name: Deploy Flutter Web to Cloudflare Pages

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Flutter version used
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web --release

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "e4f5d18aedd28895008b8e1f6845a3bc"
          projectName: "flutter-chatgpt"
          directory: build/web
